spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ecom
  datasource:
    url: jdbc:mysql://localhost:3306/ecom
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9090
  compression:
    enabled: true
    min-response-size: 6000
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json